global using BlazorComponent;
global using BlazorComponent.I18n;
global using Masa.Framework.Admin.Web.Base.Global;
global using Masa.Framework.Admin.Web.Base.Shared;
global using Masa.Framework.Sdks.Authentication.Response.Authentication.Role;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Http;
global using System.Globalization;
global using System.Text.Json;
