version: '3.4'

services:
  masa.admin.services.order:
    image: ${DOCKER_REGISTRY-}masa-services-order
    build:
      context: .
      dockerfile: src/Services/Masa.Framework.Admin.Service/Dockerfile

  masa.admin.web:
    image: ${DOCKER_REGISTRY-}masa-admin
    build:
      context: .
      dockerfile: src/Web/Masa.Framework.Admin.Web/Dockerfile

  dapr-placement:
    image: "daprio/dapr:1.5.1"
